import os

file_path = r'd:\KhoaHoc\KhoaHoc\KhoaHoc\Views\IT\Index.cshtml'

# Fix mapping: line index (0-based) -> correct string
fixes = {
    6: '    <meta name="description" content="Dashboard quản trị IT - quản lý tài khoản và hệ thống LMS" />',
    25: '        <div class="page-title" id="pageTitle">Tổng quan hệ thống</div>',
    26: '        <div class="page-subtitle" id="pageSubtitle">Giám sát và quản lý hạ tầng LMS</div>',
    30: '            🚀 Đẩy NV vào phòng ban',
    31: '        </button>',
    33: '            👤 Tạo tài khoản',
    48: '                <div class="card-header"><div class="card-title">📊 Phân bổ người dùng</div></div>',
    50: '                    <div id="userChartEmpty" style="display:none;padding:40px;text-align:center;color:#94a3b8">Chưa có dữ liệu</div>',
    55: '                <div class="card-header"><div class="card-title">🕒 Hoạt động gần đây</div></div>',
    69: '                        <span class="input-icon">🔍</span>',
    70: '                        <input id="userSearch" type="text" class="form-input with-icon" placeholder="Tìm tên, email, mã NV..." oninput="debouncedLoadUsers()">',
    81: '                            <th>Nhân viên</th>',
    82: '                            <th>Mã NV</th>',
    83: '                            <th>Phòng ban</th>',
    84: '                            <th>Trạng thái</th>',
    85: '                            <th>Thao tác</th>',
    102: '                    <span class="input-icon">🔍</span>',
    103: '                    <input id="courseSearch" type="text" class="form-input with-icon" placeholder="Tìm tên khóa học..." oninput="debouncedLoadItCourses()">',
    105: '                <button class="btn btn-primary" onclick="openCreateCourseModal()">➕ Thêm Khóa Học</button>',
    114: '                            <th>ID</th>',
    115: '                            <th>Mã KH</th>',
    116: '                            <th>Tên khóa học</th>',
    117: '                            <th>Level</th>',
    118: '                            <th>Danh mục</th>',
    119: '                            <th>Bắt buộc</th>',
    120: '                            <th>Trạng thái</th>',
    121: '                            <th>Thao tác</th>',
    135: '                <button class="btn btn-primary" onclick="openCreateDeptModal()">➕ Thêm Phòng Ban</button>',
    144: '                            <th>ID</th>',
    145: '                            <th>Tên phòng ban</th>',
    146: '                            <th>Trưởng phòng</th>',
    147: '                            <th>Số lượng NV</th>',
    148: '                            <th>Thao tác</th>',
    165: '                            <th>Thời gian</th>',
    166: '                            <th>Người thực hiện</th>',
    167: '                            <th>Hành động</th>',
    168: '                            <th>Chi tiết</th>',
    184: '                <button class="btn btn-primary" onclick="openCreateCategoryModal()">➕ Thêm Danh Mục</button>',
    192: '                            <th>ID</th><th>Tên danh mục</th><th>Khóa học</th><th>FAQ</th><th>Ngân hàng câu hỏi</th><th>Thao tác</th>',
    209: '                    <input id="faqSearch" type="text" class="form-input with-icon" placeholder="Tìm câu hỏi..." oninput="debouncedLoadFaqs()">',
    211: '                <button class="btn btn-primary" onclick="openCreateFaqModal()">➕ Thêm FAQ</button>',
    219: '                            <th style="width:40%">Câu hỏi</th><th>Câu trả lời</th><th>Danh mục</th><th>Thao tác</th>',
    235: '                    <div class="card-title">📚 Danh sách thành viên</div>',
    236: '                    <div class="card-subtitle">Quản lý kho chương, bài giảng và quiz trong toàn hệ thống.</div>',
    242: '                        <button id="libraryTabModules" class="btn btn-primary" onclick="switchLibraryTab(\'modules\')">🧩 Kho Chương</button>',
    243: '                        <button id="libraryTabLessons" class="btn btn-secondary" onclick="switchLibraryTab(\'lessons\')">📝 Kho Bài Giảng</button>',
    244: '                        <button id="libraryTabExams" class="btn btn-secondary" onclick="switchLibraryTab(\'exams\')">❓ Kho Quiz</button>',
    246: '                    <button id="libraryCreateBtn" class="btn btn-primary" onclick="openLibraryCreateModal()">➕ Tạo mới</button>',
    255: '                        <span class="input-icon">🔍</span>',
    256: '                        <input id="librarySearch" type="text" class="form-input with-icon" placeholder="Tìm theo tên chương, bài giảng, quiz hoặc khóa học..." oninput="renderDocumentLibrary()">',
    259: '                        <option value="">Tất cả khóa học</option>',
    267: '                <div class="stat-icon blue">🧩</div>',
    269: '                <div class="stat-label">Tổng số chương</div>',
    272: '                <div class="stat-icon green">📝</div>',
    274: '                <div class="stat-label">Tổng số bài giảng</div>',
    277: '                <div class="stat-icon cyan">📎</div>',
    279: '                <div class="stat-label">Tổng số tài liệu</div>',
    282: '                <div class="stat-icon orange">❓</div>',
    284: '                <div class="stat-label">Tổng số Quiz</div>',
    303: '                <div class="card-header"><div class="card-title">🏢 Nhân viên theo phòng ban</div></div>',
    307: '                <div class="card-header"><div class="card-title">📚 Khóa học theo danh mục</div></div>',
    313: '                <div class="card-header"><div class="card-title">📈 Enrollment theo tháng (6 tháng gần nhất)</div></div>',
    317: '                <div class="card-header"><div class="card-title">🎯 Tỷ lệ pass/fail Quiz</div></div>',
    325: '            <div class="card-header"><div class="card-title">🏆 Top 5 khóa học phổ biến nhất</div></div>',
    328: '                    <thead><tr><th>#</th><th>Tên khóa học</th><th>Số học viên</th></tr></thead>',
    349: '                        <button class="btn btn-primary" onclick="createBackup()">💾 Tạo Backup Ngay</button>',
    352: '                        <button class="btn btn-secondary" onclick="loadBackupLogs()">🔄 Làm mới</button>',
    359: '            <div class="card-header"><div class="card-title">📜 Lịch sử Backup</div></div>',
    363: '                        <tr><th>ID</th><th>Tên file</th><th>Loại</th><th>Thời gian tạo</th></tr>',
    378: '                    <div class="card-title">🔑 Phân quyền chức năng</div>',
    379: '                    <div class="card-subtitle">Chọn role hoặc người dùng, sau đó bấm vào từng khung để bật hoặc tắt chức năng.</div>',
    402: '                    <div style="font-size:12px;font-weight:700;color:#64748b;text-transform:uppercase;letter-spacing:.08em">Đối tượng đang chỉnh</div>',
    403: '                    <div id="permissionBoardTitle" style="margin-top:6px;font-size:18px;font-weight:800;color:#0f172a">Chưa chọn đối tượng</div>',
    407: '                    <div style="padding:24px;color:#94a3b8;text-align:center;grid-column:1/-1">Đang tải danh sách chức năng...</div>',
    416: '                <div class="card-title">⚙️ Cài đặt hệ thống</div>',
    417: '                <button class="btn btn-secondary btn-sm" onclick="loadSettings()">Làm mới</button>',
    422: '                        <tr><th>Khóa</th><th>Giá trị</th><th>Cập nhật lần cuối</th><th>Thao tác</th></tr>',
    436: '            <div class="card-header"><div class="card-title">📧 Danh sách đăng ký Newsletter</div></div>',
    440: '                        <tr><th>Họ tên</th><th>Mã NV</th><th>Chức danh</th><th>Thao tác</th></tr>',
    457: '                <div style="font-size:13px;color:#64748b">Quản lý chức danh nhân viên trong hệ thống</div>',
    458: '                <button class="btn btn-primary" onclick="openCreateJobTitleModal()">➕ Thêm Chức Danh</button>',
    465: '                        <tr><th>ID</th><th>Tên Chức Danh</th><th>Cấp Bậc (Grade)</th><th>Số NV Đang Dùng</th><th>Thao tác</th></tr>',
    479: '                <div class="card-header"><div class="card-title">📥 Xuất Danh Sách Nhân Viên</div></div>',
    481: '                    <p style="font-size:13px;color:#64748b;margin-bottom:16px">Xuất toàn bộ danh sách nhân viên ra file Excel bao gồm phòng ban, chức danh, roles.</p>',
    483: '                        <label style="font-size:12px;font-weight:600">Lọc theo trạng thái</label>',
    485: '                            <option value="">Tất cả</option>',
    494: '                <div class="card-header"><div class="card-title">📈 Báo Cáo Đào Tạo</div></div>',
    496: '                    <p style="font-size:13px;color:#64748b;margin-bottom:16px">Xuất báo cáo phân công đào tạo, trạng thái hoàn thành, hạn nộp theo từng nhân viên.</p>',
    497: '                    <div style="background:rgba(16,185,129,0.08);border:1px solid rgba(16,185,129,0.3);border-radius:8px;padding:10px;margin-bottom:16px;font-size:12px;color:#065f46">💡 Các dòng quá hạn sẽ được tô đỏ trong Excel</div>',
    502: '                <div class="card-header"><div class="card-title">📝 Kết Quả Bài Kiểm Tra</div></div>',
    504: '                    <p style="font-size:13px;color:#64748b;margin-bottom:16px">Xuất kết quả bài kiểm tra đã hoàn thành, điểm số và kết quả Đạt/Không Đạt.</p>',
    505: '                    <div style="background:rgba(239,68,68,0.08);border:1px solid rgba(239,68,68,0.3);border-radius:8px;padding:10px;margin-bottom:16px;font-size:12px;color:#7f1d1d">❌ Kết quả Không Đạt sẽ được tô đỏ</div>',
    510: '        <div id="exportMsg" style="margin-top:16px;padding:12px 20px;background:rgba(59,130,246,0.08);border:1px solid rgba(59,130,246,0.3);border-radius:8px;font-size:13px;color:#1e40af;display:none">⏳ Đang tạo file Excel, vui lòng chờ ...</div>',
    518: '        <div class="modal-header"><div class="modal-title" id="jobTitleModalTitle">➕ Thêm Chức Danh</div><button class="modal-close" onclick="closeModal(\'jobTitleModal\')">✖</button></div>',
    521: '            <div class="form-group"><label>Tên Chức Danh *</label><input id="jobTitleModalName" type="text" class="form-input" placeholder="VD: Nhân viên kinh doanh, Trưởng phòng..."></div>',
    525: '                <div style="font-size:11px;color:#94a3b8;margin-top:4px">Số càng cao = cấp bậc càng cao.</div>',
    535: '        <div class="modal-header"><div class="modal-title">👤 Tạo tài khoản</div><button class="modal-close" onclick="closeModal(\'createUserModal\')">✖</button></div>',
    537: '            <div class="form-group"><label>Tên đăng nhập</label><input id="newUsername" type="text" class="form-input"></div>',
    538: '            <div class="form-group"><label>Mật khẩu</label><input id="newPassword" type="password" class="form-input" value="123"></div>',
    539: '            <div class="form-group"><label>Họ và tên</label><input id="newFullName" type="text" class="form-input"></div>',
    540: '            <div class="form-group"><label>Giảng viên</label><input id="scheduleInstructor" class="form-input" placeholder="VD: Nguyễn Văn A"></div>',
    551: '        <div class="modal-header"><div class="modal-title">📝 Sửa tài khoản</div><button class="modal-close" onclick="closeModal(\'editUserModal\')">✖</button></div>',
    554: '            <div class="form-group"><label>Họ và tên</label><input id="editFullName" type="text" class="form-input"></div>',
    562: '            <div class="form-group"><label>Mật khẩu mới (Nếu đổi)</label><input id="editPassword" type="password" class="form-input"></div>',
    570: '        <div class="modal-header"><div class="modal-title">Phân quyền người dùng</div><button class="modal-close" onclick="closeModal(\'userRoleModal\')">✖</button></div>',
    583: '        <div class="modal-header"><div class="modal-title" id="courseModalTitle">Tạo khóa học</div><button class="modal-close" onclick="closeModal(\'courseModal\')">✖</button></div>',
    586: '                <label class="form-label" style="color: #7c3aed;">🚀 Tạo tự động bằng AI</label>',
    593: '            <div class="form-group"><label>Mã khóa học *</label><input id="courseModalCodeInput" type="text" class="form-input" placeholder="VD: IT201"></div>',
    594: '            <div class="form-group"><label>Level</label><select id="courseModalLevel" class="form-input"><option value="">-- Chọn level --</option><option value="1">Level 1</option><option value="2">Level 2</option><option value="3">Level 3</option></select></div>',
    595: '            <div class="form-group"><label>Tên khóa học *</label><input id="courseModalTitleInput" type="text" class="form-input"></div>',
    596: '            <div class="form-group"><label>Mô tả</label><textarea id="courseModalDesc" class="form-input" rows="3"></textarea></div>',
    598: '                <div class="form-group"><label>Ngày bắt đầu</label><input id="courseModalStartDate" type="date" class="form-input"></div>',
    599: '                <div class="form-group"><label>Ngày kết thúc</label><input id="courseModalEndDate" type="date" class="form-input"></div>',
    617: '                <label for="courseModalMandatory" style="margin:0;cursor:pointer">Bắt buộc đối với phòng ban trên</label>',
    640: '            <button class="modal-close" onclick="closeModal(\'departmentDetailModal\')">✖</button>',
    728: '                <div class="modal-title" id="contentModalTitle">Xây dựng nội dung khóa học</div>',
    791: '                        <div style="font-weight:600; font-size:16px;">Khóa học này chưa có nội dung</div>',
    792: '                        <div style="font-size:13px;">Hãy kéo Chương, Bài giảng hoặc Quiz từ thư viện bên trái vào đây</div>',
    801: '        <div class="modal-header"><div class="modal-title">Thêm Chương Mới</div><button class="modal-close" onclick="closeModal(\'moduleModal\')">✖</button></div>',
    804: '                <label class="form-label" style="color: #6366f1;">💡 Gợi ý chương từ AI</label>',
    808: '                    <button class="btn btn-primary" style="background: linear-gradient(135deg, #6366f1, #4f46e5); border:none;" onclick="generateModuleWithAI(\'module\')" id="btnGenerateModuleAI">Gợi ý</button>',
    821: '        <div class="modal-header"><div class="modal-title">Thêm Bài Học</div><button class="modal-close" onclick="closeModal(\'lessonModal\')">✖</button></div>',
    824: '                <label class="form-label" style="color: #10b981;">📝 Soạn bài giảng bằng AI</label>',
    852: '        <div class="modal-header"><div class="modal-title">Tạo Bài Kiểm Tra</div><button class="modal-close" onclick="closeModal(\'examModal\')">✖</button></div>',
    855: '                <label class="form-label" style="color: #f59e0b;">❓ Tạo Quiz tự động bằng AI</label>',
    885: '        <div class="modal-header"><div class="modal-title">Thêm Câu Hỏi Mới</div><button class="modal-close" onclick="closeModal(\'questionModal\')">✖</button></div>',
    891: '                <button class="btn btn-primary" style="background: linear-gradient(135deg, #6366f1, #4f46e5); border:none; white-space: nowrap;" onclick="suggestQuestionWithAI()" id="btnSuggestQuestionAI">💡 AI Gợi ý</button>',
    893: '            <div class="form-group"><label>Nội dung câu hỏi *</label><textarea id="qTextInput" class="form-input" rows="2"></textarea></div>',
    894: '            <div class="form-group"><label>Điểm</label><input id="qPointsInput" type="number" class="form-input" value="10"></div>',
    895: '            <div class="form-group"><label>Các đáp án (Chọn 1 đáp án đúng)</label>',
    898: '                    <input type="text" id="qOpt1" class="form-input" placeholder="Đáp án A">',
    902: '                    <input type="text" id="qOpt2" class="form-input" placeholder="Đáp án B">',
    906: '                    <input type="text" id="qOpt3" class="form-input" placeholder="Đáp án C">',
    910: '                    <input type="text" id="qOpt4" class="form-input" placeholder="Đáp án D">',
    913: '        <div class="modal-footer"><button class="btn btn-primary" onclick="submitQuestion()">💾 Lưu Câu Hỏi</button></div>',
    920: '        <div class="modal-header"><div class="modal-title" id="categoryModalTitle">Thêm danh mục</div><button class="modal-close" onclick="closeModal(\'categoryModal\')">✖</button></div>',
    933: '        <div class="modal-header"><div class="modal-title" id="faqModalTitle">Thêm FAQ</div><button class="modal-close" onclick="closeModal(\'faqModal\')">✖</button></div>',
    947: '        <div class="modal-header"><div class="modal-title">Sửa Chương Học</div><button class="modal-close" onclick="closeModal(\'editModuleModal\')">✖</button></div>',
    960: '        <div class="modal-header"><div class="modal-title">Sửa Bài Học</div><button class="modal-close" onclick="closeModal(\'editLessonModal\')">✖</button></div>',
    983: '        <div class="modal-header"><div class="modal-title">Sửa Bài Kiểm Tra</div><button class="modal-close" onclick="closeModal(\'editExamModal\')">✖</button></div>',
    1008: '        <div class="modal-header"><div class="modal-title">Tạo Chương Mới</div><button class="modal-close" onclick="closeModal(\'libraryModuleModal\')">✖</button></div>',
    1012: '                <label class="form-label" style="color: #6366f1;">💡 Gợi ý chương từ AI</label>',
    1030: '        <div class="modal-header"><div class="modal-title">Tạo Bài Giảng Mới</div><button class="modal-close" onclick="closeModal(\'libraryLessonModal\')">✖</button></div>',
    1034: '                <label class="form-label" style="color: #10b981;">📝 Soạn bài giảng bằng AI</label>',
    1057: '        <div class="modal-header"><div class="modal-title">Tạo Quiz Mới</div><button class="modal-close" onclick="closeModal(\'libraryExamModal\')">✖</button></div>',
    1061: '                <label class="form-label" style="color: #f59e0b;">❓ Tạo Quiz tự động bằng AI</label>',
    1091: '        <div class="modal-header"><div class="modal-title">Cập nhật quyền theo role</div><button class="modal-close" onclick="closeModal(\'permissionModal\')">✖</button></div>',
    1104: '        <div class="modal-header"><div class="modal-title">Cập nhật cài đặt</div><button class="modal-close" onclick="closeModal(\'settingModal\')">✖</button></div>',
    1116: '        <div class="modal-header"><div class="modal-title" id="scheduleModalTitle">Thêm lịch học</div><button class="modal-close" onclick="closeModal(\'scheduleModal\')">✖</button></div>'
}

with open(file_path, 'r', encoding='utf-8', errors='ignore') as f:
    lines = f.readlines()

for idx, correct_text in fixes.items():
    if idx < len(lines):
        lines[idx] = correct_text + '\n'

with open(file_path, 'w', encoding='utf-8-sig') as f:
    f.writelines(lines)

print(f"Fixed {len(fixes)} lines in {file_path}")
